Change os.tmpDir() to os.tmpdir() in Grunttasks.ts
The 'grunt release' command in the installation instructions fails on OS X with the following error:

    error TS2339: Property 'tmpDir' does not exist on type 'typeof "os"'.

This is fixed by changing the case of os.tmpDir() to os.tmpdir(), which is the correct name of the function: http://nodejs.org/api/os.html#os_os_tmpdir